/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppMcpRouteImport } from './routes/_app.mcp'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppDomainsIndexRouteImport } from './routes/_app.domains.index'
import { Route as AppCredentialsIndexRouteImport } from './routes/_app.credentials.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppRunsRunIdRouteImport } from './routes/_app.runs.$runId'
import { Route as AppDomainsNewRouteImport } from './routes/_app.domains.new'
import { Route as AppDomainRunsRunIdRouteImport } from './routes/_app.domain-runs.$runId'
import { Route as AppDomainPlansPlanIdRouteImport } from './routes/_app.domain-plans.$planId'
import { Route as AppCredentialsNewRouteImport } from './routes/_app.credentials.new'
import { Route as AppCredentialsIdRouteImport } from './routes/_app.credentials.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsIndexRoute = AppDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsIndexRoute = AppCredentialsIndexRouteImport.update({
  id: '/credentials/',
  path: '/credentials/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsNewRoute = AppDomainsNewRouteImport.update({
  id: '/domains/new',
  path: '/domains/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainRunsRunIdRoute = AppDomainRunsRunIdRouteImport.update({
  id: '/domain-runs/$runId',
  path: '/domain-runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainPlansPlanIdRoute = AppDomainPlansPlanIdRouteImport.update({
  id: '/domain-plans/$planId',
  path: '/domain-plans/$planId',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsNewRoute = AppCredentialsNewRouteImport.update({
  id: '/credentials/new',
  path: '/credentials/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsIdRoute = AppCredentialsIdRouteImport.update({
  id: '/credentials/$id',
  path: '/credentials/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/mcp': typeof AppMcpRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/credentials/$id': typeof AppCredentialsIdRoute
  '/credentials/new': typeof AppCredentialsNewRoute
  '/domain-plans/$planId': typeof AppDomainPlansPlanIdRoute
  '/domain-runs/$runId': typeof AppDomainRunsRunIdRoute
  '/domains/new': typeof AppDomainsNewRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/credentials/': typeof AppCredentialsIndexRoute
  '/domains/': typeof AppDomainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/mcp': typeof AppMcpRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/credentials/$id': typeof AppCredentialsIdRoute
  '/credentials/new': typeof AppCredentialsNewRoute
  '/domain-plans/$planId': typeof AppDomainPlansPlanIdRoute
  '/domain-runs/$runId': typeof AppDomainRunsRunIdRoute
  '/domains/new': typeof AppDomainsNewRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/credentials': typeof AppCredentialsIndexRoute
  '/domains': typeof AppDomainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mcp': typeof AppMcpRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/_app/credentials/$id': typeof AppCredentialsIdRoute
  '/_app/credentials/new': typeof AppCredentialsNewRoute
  '/_app/domain-plans/$planId': typeof AppDomainPlansPlanIdRoute
  '/_app/domain-runs/$runId': typeof AppDomainRunsRunIdRoute
  '/_app/domains/new': typeof AppDomainsNewRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/credentials/': typeof AppCredentialsIndexRoute
  '/_app/domains/': typeof AppDomainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/audit'
    | '/dashboard'
    | '/mcp'
    | '/api/health'
    | '/api/mcp'
    | '/credentials/$id'
    | '/credentials/new'
    | '/domain-plans/$planId'
    | '/domain-runs/$runId'
    | '/domains/new'
    | '/runs/$runId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/credentials/'
    | '/domains/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/audit'
    | '/dashboard'
    | '/mcp'
    | '/api/health'
    | '/api/mcp'
    | '/credentials/$id'
    | '/credentials/new'
    | '/domain-plans/$planId'
    | '/domain-runs/$runId'
    | '/domains/new'
    | '/runs/$runId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/credentials'
    | '/domains'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/mcp'
    | '/api/health'
    | '/api/mcp'
    | '/_app/credentials/$id'
    | '/_app/credentials/new'
    | '/_app/domain-plans/$planId'
    | '/_app/domain-runs/$runId'
    | '/_app/domains/new'
    | '/_app/runs/$runId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_app/credentials/'
    | '/_app/domains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/mcp': {
      id: '/_app/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains/': {
      id: '/_app/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof AppDomainsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/': {
      id: '/_app/credentials/'
      path: '/credentials'
      fullPath: '/credentials/'
      preLoaderRoute: typeof AppCredentialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains/new': {
      id: '/_app/domains/new'
      path: '/domains/new'
      fullPath: '/domains/new'
      preLoaderRoute: typeof AppDomainsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domain-runs/$runId': {
      id: '/_app/domain-runs/$runId'
      path: '/domain-runs/$runId'
      fullPath: '/domain-runs/$runId'
      preLoaderRoute: typeof AppDomainRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domain-plans/$planId': {
      id: '/_app/domain-plans/$planId'
      path: '/domain-plans/$planId'
      fullPath: '/domain-plans/$planId'
      preLoaderRoute: typeof AppDomainPlansPlanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/new': {
      id: '/_app/credentials/new'
      path: '/credentials/new'
      fullPath: '/credentials/new'
      preLoaderRoute: typeof AppCredentialsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/$id': {
      id: '/_app/credentials/$id'
      path: '/credentials/$id'
      fullPath: '/credentials/$id'
      preLoaderRoute: typeof AppCredentialsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMcpRoute: typeof AppMcpRoute
  AppCredentialsIdRoute: typeof AppCredentialsIdRoute
  AppCredentialsNewRoute: typeof AppCredentialsNewRoute
  AppDomainPlansPlanIdRoute: typeof AppDomainPlansPlanIdRoute
  AppDomainRunsRunIdRoute: typeof AppDomainRunsRunIdRoute
  AppDomainsNewRoute: typeof AppDomainsNewRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppCredentialsIndexRoute: typeof AppCredentialsIndexRoute
  AppDomainsIndexRoute: typeof AppDomainsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMcpRoute: AppMcpRoute,
  AppCredentialsIdRoute: AppCredentialsIdRoute,
  AppCredentialsNewRoute: AppCredentialsNewRoute,
  AppDomainPlansPlanIdRoute: AppDomainPlansPlanIdRoute,
  AppDomainRunsRunIdRoute: AppDomainRunsRunIdRoute,
  AppDomainsNewRoute: AppDomainsNewRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppCredentialsIndexRoute: AppCredentialsIndexRoute,
  AppDomainsIndexRoute: AppDomainsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
