/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCredentialsIndexRouteImport } from './routes/_app.credentials.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppRunsRunIdRouteImport } from './routes/_app.runs.$runId'
import { Route as AppCredentialsNewRouteImport } from './routes/_app.credentials.new'
import { Route as AppCredentialsIdRouteImport } from './routes/_app.credentials.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsIndexRoute = AppCredentialsIndexRouteImport.update({
  id: '/credentials/',
  path: '/credentials/',
  getParentRoute: () => AppRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsNewRoute = AppCredentialsNewRouteImport.update({
  id: '/credentials/new',
  path: '/credentials/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsIdRoute = AppCredentialsIdRouteImport.update({
  id: '/credentials/$id',
  path: '/credentials/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/credentials/$id': typeof AppCredentialsIdRoute
  '/credentials/new': typeof AppCredentialsNewRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/credentials/': typeof AppCredentialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/credentials/$id': typeof AppCredentialsIdRoute
  '/credentials/new': typeof AppCredentialsNewRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/credentials': typeof AppCredentialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/credentials/$id': typeof AppCredentialsIdRoute
  '/_app/credentials/new': typeof AppCredentialsNewRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_app/credentials/': typeof AppCredentialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/api/health'
    | '/credentials/$id'
    | '/credentials/new'
    | '/runs/$runId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/credentials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/api/health'
    | '/credentials/$id'
    | '/credentials/new'
    | '/runs/$runId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/credentials'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/api/health'
    | '/_app/credentials/$id'
    | '/_app/credentials/new'
    | '/_app/runs/$runId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_app/credentials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/': {
      id: '/_app/credentials/'
      path: '/credentials'
      fullPath: '/credentials/'
      preLoaderRoute: typeof AppCredentialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/new': {
      id: '/_app/credentials/new'
      path: '/credentials/new'
      fullPath: '/credentials/new'
      preLoaderRoute: typeof AppCredentialsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/$id': {
      id: '/_app/credentials/$id'
      path: '/credentials/$id'
      fullPath: '/credentials/$id'
      preLoaderRoute: typeof AppCredentialsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppCredentialsIdRoute: typeof AppCredentialsIdRoute
  AppCredentialsNewRoute: typeof AppCredentialsNewRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppCredentialsIndexRoute: typeof AppCredentialsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppCredentialsIdRoute: AppCredentialsIdRoute,
  AppCredentialsNewRoute: AppCredentialsNewRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppCredentialsIndexRoute: AppCredentialsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
